const codes = {
    AFN: "Afghani",
    ALL: "Albanian Lek",
    DZD: "Algerian Dinar",
    ARS: "Argentine Peso",
    AMD: "Armenian Dram",
    AWG: "Aruban Florin",
    AUD: "Australian Dollar",
    AZN: "Azerbaijanian Manat",
    BSD: "Bahamian Dollar",
    BHD: "Bahraini Dinar",
    THB: "Baht",
    PAB: "Balboa",
    BDT: "Bangladeshi Taka",
    BBD: "Barbados Dollar",
    BYR: "Belarussian Ruble",
    BZD: "Belize Dollar",
    BMD: "Bermudian Dollar",
    BTN: "Bhutanese Ngultrum",
    VES: "Bolívar Soberano",
    BOB: "Boliviano",
    BWP: "Botswana Pula",
    BRL: "Brazilian Real",
    BND: "Brunei Dollar",
    BGN: "Bulgarian Lev",
    BIF: "Burundi Franc",
    CAD: "Canadian Dollar",
    CVE: "Cape Verde Escudo",
    KYD: "Cayman Islands Dollar",
    XOF: "CFA Franc BCEAO",
    XAF: "CFA Franc BEAC",
    XPF: "CFP Franc",
    CLP: "Chilean Peso",
    COP: "Colombian Peso",
    KMF: "Comoro Franc",
    CDF: "Congolese Franc",
    BAM: "Convertible Mark",
    NIO: "Cordoba Oro",
    CRC: "Costa Rican Colon",
    HRK: "Croatian Kuna",
    CUP: "Cuban Peso",
    CZK: "Czech Koruna",
    GMD: "Dalasi",
    DKK: "Danish Krone",
    MKD: "Denar",
    DJF: "Djibouti Franc",
    STD: "Sao Tomean Dobra",
    STN: "Príncipe Dobra",
    DOP: "Dominican Peso",
    VND: "Dong",
    XCD: "East Caribbean Dollar",
    EGP: "Egyptian Pound",
    SVC: "El Salvador Colon",
    ETB: "Ethiopian Birr",
    EUR: "Euro",
    FKP: "Falkland Islands Pound",
    FJD: "Fiji Dollar",
    HUF: "Forint",
    GHS: "Ghana Cedi",
    GIP: "Gibraltar Pound",
    HTG: "Gourde",
    PYG: "Guarani",
    GNF: "Guinea Franc",
    GYD: "Guyana Dollar",
    HKD: "Hong Kong Dollar",
    UAH: "Hryvnia",
    ISK: "Iceland Krona",
    INR: "Indian Rupee",
    IQD: "Iraqi Dinar",
    JMD: "Jamaican Dollar",
    JOD: "Jordanian Dinar",
    KES: "Kenyan Shilling",
    PGK: "Kina",
    LAK: "Kip",
    KWD: "Kuwaiti Dinar",
    MWK: "Kwacha",
    AOA: "Kwanza",
    MMK: "Kyat",
    KGS: "Kyrgyzstan Soma",
    GEL: "Lari",
    LBP: "Lebanese Pound",
    HNL: "Lempira",
    SLL: "Leone",
    LRD: "Liberian Dollar",
    LYD: "Libyan Dinar",
    SZL: "Lilangeni",
    LSL: "Loti",
    MGA: "Malagasy Ariary",
    MYR: "Malaysian Ringgit",
    MUR: "Mauritius Rupee",
    MXN: "Mexican Peso",
    MDL: "Moldovan Leu",
    MAD: "Moroccan Dirham",
    MZN: "Mozambique Metical",
    NGN: "Naira",
    NAD: "Namibia Dollar",
    NPR: "Nepalese Rupee",
    ANG: "Netherlands Antillean Guilder",
    ILS: "New Israeli Sheqel",
    RON: "New Romanian Leu",
    TWD: "New Taiwan Dollar",
    NZD: "New Zealand Dollar",
    NOK: "Norwegian Krone",
    PEN: "Nuevo Sol",
    MRO: "Ouguiya",
    MRU: "Ouguiya",
    TOP: "PaÃ¢â‚¬â„¢anga",
    PKR: "Pakistan Rupee",
    MOP: "Pataca",
    UYU: "Peso Uruguayo",
    PHP: "Philippine Peso",
    GBP: "Pound Sterling",
    QAR: "Qatari Rial",
    GTQ: "Quetzal",
    ZAR: "Rand",
    OMR: "Rial Omani",
    KHR: "Riel",
    MVR: "Rufiyaa",
    IDR: "Rupiah",
    RUB: "Russian Ruble",
    RWF: "Rwanda Franc",
    SHP: "Saint Helena Pound",
    SAR: "Saudi Riyal",
    RSD: "Serbian Dinar",
    SCR: "Seychelles Rupee",
    SGD: "Singapore Dollar",
    SBD: "Solomon Islands dollar",
    SOS: "Somali Shilling",
    TJS: "Somoni",
    SSP: "South Sudanese Pound",
    LKR: "Sri Lanka Rupee",
    SDG: "Sudanese Pound",
    SRD: "Surinam Dollar",
    SEK: "Swedish Krona",
    CHF: "Swiss Franc",
    WST: "Tala",
    TZS: "Tanzanian Shilling",
    KZT: "Tenge",
    TTD: "Trinidad and Tobago Dollar",
    MNT: "Tugrik",
    TND: "Tunisian Dinar",
    TRY: "Turkish Lira",
    TMT: "Turkmenistan New Manat",
    AED: "UAE Dirham",
    UGX: "Uganda Shilling",
    CLF: "Unidades de Fomento",
    USD: "US Dollar",
    UZS: "Uzbekistan Sum",
    VUV: "Vatu",
    KRW: "Won",
    YER: "Yemeni Rial",
    JPY: "Yen",
    CNY: "Yuan Renminbi",
    ZMW: "Zambian Kwacha",
    PLN: "Zloty"
}